### ISSUE TITLE
Can you add the "purrr" package to the default load package list?

### ISSUE THREAD

**Issue by tianranchunzhen** [psychbruce/bruceR#21]
just like the title.

**Comment by psychbruce** [comment]
Thanks for suggesting this. I'm sorry I can't. `bruceR` does not use any function of `purrr` (though I do know it is useful), so this package is not listed in the "Imports" field (see the [DESCRIPTION](https://github.com/psychbruce/bruceR/blob/main/DESCRIPTION) file). All packages listed in "Imports" should be used at least once, which is required for package developers (see https://cran.r-project.org/doc/manuals/R-exts.html). Also, the selection of default loaded packages depends on my own preference, and I suggest users using `data.table` instead of depending overly on `tidyverse`. That's just my personal preference and I can't satisfy everyone's unique requirement.
