### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JJery-web** [psychbruce/bruceR#26]
Hello, thank you very much for your contribution and effort.

I am a beginner in using the R language. I managed to install the **bruceR package** with the help of various online resources. I would like to know if there are **any tutorials available** that can help me quickly get started with bruceR. 

For example, I would like to learn how to convert certain text into word vectors or perform similarity calculations.

I'm sorry for the interruption. Best wishes to you.

**Comment by psychbruce** [comment]
Thanks. The official website and help pages (R documentations) are the best tutorials for learning a package, including `bruceR`. You also mentioned word vectors and similarity calculation, but these are within the scope of `PsychWordVec`, another package I developed, rather than `bruceR`. While `bruceR` provides a miscellaneous toolbox mainly for basic R programming and common statistical analyses, `PsychWordVec` is designed particularly for word vectors processing and related analyses. Each package has their own specific functionality and please do not mix them up.

So please refer to their websites and help pages:
- `bruceR`: https://psychbruce.github.io/bruceR/
- `PsychWordVec`: https://psychbruce.github.io/PsychWordVec/

From these websites, you can easily find what a function can do. There are no all-in-one tutorials. You should know your analytic purpose and use the proper function(s). I believe these materials have explained clearly the functionality.

Not sure if you are a Chinese; if so, you may find my [Zhihu articles](https://www.zhihu.com/people/psychbruce/posts) helpful as well, especially the Chinese documentation of `bruceR` (https://zhuanlan.zhihu.com/p/281150493).

For R beginners, learning `bruceR` is helpful but not enough. You should also learn `tidyverse` (esp. `dplyr`, `stringr`, `ggplot2` packages) and the `data.table` package (beyond what I can help). Please search the Internet for tutorials for these more basic packages.

**Comment by JJery-web** [comment]
Thank you so much!
