### ISSUE TITLE
How do I save the pairwise contrasts from a MANOVA() %>% EMMEANS pipe?

### ISSUE THREAD

**Issue by BenJCQuah** [psychbruce/bruceR#29]
Hi, thanks for the great package,

Sorry this is probably an easy query, but I can't seem to find a good way to save the contrast from a pairwise EMMEANS comparison to a word or png file.

For example if I run a code like:

MANOVA(man_test_data, dvs="Sample_019:Sample_135", dvs.pattern="Sample(.+)",
       between="control_type", within="Sample",
       sph.correction="GG") %>%
       EMMEANS("control_type") 

It generates a great set of statistics but how do I save these as a word or table for publication?  Especially the contrast, which don't appear to be in the EMMEANS slot.

Sorry if this is an obvious thing to do, but I am new to  EMMEANS  analysis.

Thanks!

**Comment by psychbruce** [comment]
Thank you. `EMMEANS()` does not provide a `file` parameter, this is an intentional design because there are multiple tables in its output with a disclaimer that should be noted. Please just make a table manually for publication. See https://psychbruce.github.io/bruceR/#function-output to check if a function supports MS Word output.
